### ISSUE TITLE
Что  такое 0 и 1? Почему именно 1 и 2 элементы? И зачем нужно 2 цикла? Почему нельзя сразу проверить пересечение внутри цикла, находящегося в функции getObjAreas?

### ISSUE THREAD

**Issue by frontgirl** [kosiginiv83/dip_ex#3]
https://github.com/kosiginiv83/dip_ex/blob/96204663fce2369c83ca95fd610e93fe9925cc39/js-game-1.4.1/game.js#L151

**Comment by kosiginiv83** [comment]
Переписал, чтобы было явно.
Усложненная логика на тот случай, если будет столкновение с несколькими препятствиями одновременно, чтобы приоритет был за лавой.
